{{- if .Values.multus.f1Interface.create }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Chart.Name }}-f1
spec:
  config: |-
    {
          "cniVersion": "0.3.0",
          "name": "gnb-n2",
          "type": "macvlan",
          "master": {{- cat .Values.multus.f1Interface.hostInterface | nospace | quote }},
          "mode": "bridge",
          "ipam": {
            "type": "whereabouts"
          }
    }
{{- end }}

