---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  nr-ue.conf: |
      uicc0 = {
      imsi = "{{ .Values.config.fullImsi }}";
      key = "{{ .Values.config.fullKey }}";
      opc= "{{ .Values.config.opc }}";
      dnn= "{{ .Values.config.dnn }}";
      nssai_sst="{{ .Values.config.sst }}";
      nssai_sd="{{ .Values.config.sd }}";
      }

      log_config = {
        global_log_level                      ="info";
        hw_log_level                          ="info";
        phy_log_level                         ="info";
        mac_log_level                         ="debug";
        rlc_log_level                         ="debug";
        pdcp_log_level                        ="debug";
        rrc_log_level                         ="debug";
      };

