apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: oai-gnb-n3
  namespace: oai-ran
spec:
  config: |-
    {
          "cniVersion": "0.3.0",
          "name": "gnb-n3",
          "type": "macvlan",
          "master": "enp1s0",
          "mode": "bridge",
          "ipam": {
            "type": "whereabouts"
          }
    }

