kind: Deployment
apiVersion: apps/v1
metadata:
  name: oai-gnb-argocd
  namespace: oai-ran
  labels:
    helm.sh/chart: oai-gnb-argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: gnb
      app.kubernetes.io/name: oai-gnb
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: oai-gnb
        app.kubernetes.io/instance: gnb
        app.kubernetes.io/name: oai-gnb
      annotations:
        k8s.v1.cni.cncf.io/networks: |-
          [{
                 "name": "oai-gnb-n2-wa",
                 "ips":["172.2.2.100/24"],
                 "interface": "n2"
          } ,{
                 "name": "oai-gnb-n3",
                 "interface": "n3",
                 "ips": ["172.3.0.200/24"]
          } ]
    spec:
      containers:
        - name: gnb
          image: docker.io/oaisoftwarealliance/oai-gnb:2023.w19
          ports:
            - name: n3
              containerPort: 2152
              protocol: UDP
            - name: n2
              containerPort: 36412
              protocol: SCTP
          env:
            - name: TZ
              value: Europe/Paris
            - name: RFSIMULATOR
              value: server
            - name: USE_ADDITIONAL_OPTIONS
              value: >-
                --sa -E --rfsim --log_config.global_log_options
                level,nocolor,time
            - name: USE_SA_TDD_MONO
              valueFrom:
                configMapKeyRef:
                  name: oai-gnb-configmap
                  key: useSATddMono
            - name: GNB_ID
              valueFrom:
                configMapKeyRef:
                  name: oai-gnb-configmap
                  key: gnbID
            - name: GNB_NAME
              valueFrom:
                configMapKeyRef:
                  name: oai-gnb-configmap
                  key: gnbName
            - name: MCC
              valueFrom:
                configMapKeyRef:
                  name: oai-gnb-configmap
                  key: mcc
            - name: MNC
              valueFrom:
                configMapKeyRef:
                  name: oai-gnb-configmap
                  key: mnc
            - name: MNC_LENGTH
              valueFrom:
                configMapKeyRef:
                  name: oai-gnb-configmap
                  key: mncLength
            - name: TAC
              valueFrom:
                configMapKeyRef:
                  name: oai-gnb-configmap
                  key: tac
            - name: NSSAI_SST
              valueFrom:
                configMapKeyRef:
                  name: oai-gnb-configmap
                  key: nssaiSst
            - name: NSSAI_SD0
              valueFrom:
                configMapKeyRef:
                  name: oai-gnb-configmap
                  key: nssaiSd0
            - name: AMF_IP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: oai-gnb-configmap
                  key: amfIpAddress
            - name: GNB_NGA_IF_NAME
              valueFrom:
                configMapKeyRef:
                  name: oai-gnb-configmap
                  key: gnbNgaIfName
            - name: GNB_NGA_IP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: oai-gnb-configmap
                  key: gnbNgaIpAddress
            - name: GNB_NGU_IF_NAME
              valueFrom:
                configMapKeyRef:
                  name: oai-gnb-configmap
                  key: gnbNguIfName
            - name: GNB_NGU_IP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: oai-gnb-configmap
                  key: gnbNguIpAddress
            - name: THREAD_PARALLEL_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: oai-gnb-configmap
                  key: threadParallelConfig
            - name: SDR_ADDRS
              valueFrom:
                configMapKeyRef:
                  name: oai-gnb-configmap
                  key: sdrAddrs
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
      dnsPolicy: ClusterFirst
      serviceAccountName: oai-gnb-sa
      serviceAccount: oai-gnb-sa
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      imagePullSecrets:
        - name: regcred
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

