---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap-pnf
data:
  du.conf: |
    
    ########################################################################################3
    log_config = {
      global_log_level                      ="info";
      hw_log_level                          ="info";
      phy_log_level                         ="info";
      mac_log_level                         ="debug";
      rlc_log_level                         ="debug";
      pdcp_log_level                        ="debug";
      rrc_log_level                         ="debug";
    };
    
    L1s = (
        {
    	num_cc = 1;
    	tr_n_preference = "nfapi";
        local_n_if_name  = "nfapi";
        remote_n_address = "@VNF_IP_ADDRESS@";
        local_n_address  = "@PNF_IP_ADDRESS@";
        local_n_portc    = 50000;
        remote_n_portc   = 50001;
        local_n_portd    = 50010;
        remote_n_portd   = 50011;
        }  
    );
    
    RUs = (
        {		  
           local_rf       = "yes"
           sl_ahead = 5;
           nb_tx          = 1
           nb_rx          = 1
           att_tx         = 0
           att_rx         = 0;
           bands          = [78];
           max_pdschReferenceSignalPower = -27;
           max_rxgain                    = 125;
        }		      
    );
    
    
    THREAD_STRUCT = (
    {
      #three config for level of parallelism "PARALLEL_SINGLE_THREAD", "PARALLEL_RU_L1_SPLIT", or "PARALLEL_RU_L1_TRX_SPLIT"
      parallel_config    = "PARALLEL_SINGLE_THREAD";
      #two option for worker "WORKER_DISABLE" or "WORKER_ENABLE"
      worker_config      = "WORKER_ENABLE";
    }
    );
