---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-wa
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": {{- cat .Values.multus.f1Interface.hostInterface | nospace | quote }},
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts"
      }
    }'
