kind: Deployment
apiVersion: apps/v1
metadata:
  name: oai-nr-ue-argocd
  namespace: oai-ran
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: nrue
      app.kubernetes.io/name: oai-nr-ue
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: oai-nr-ue
        app.kubernetes.io/instance: nrue
        app.kubernetes.io/name: oai-nr-ue
    spec:
      containers:
        - name: nr-ue
          image: docker.io/oaisoftwarealliance/oai-nr-ue:2023.w19
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: oai-nr-ue-configmap
                  key: timeZone
            - name: RFSIMULATOR
              valueFrom:
                configMapKeyRef:
                  name: oai-nr-ue-configmap
                  key: rfSimulator
            - name: FULL_IMSI
              value: '001010000000102'
            - name: FULL_KEY
              value: 'oai-gnb-argocd'
            - name: OPC
              valueFrom:
                configMapKeyRef:
                  name: oai-nr-ue-configmap
                  key: opc
            - name: DNN
              value: internet
            - name: NSSAI_SST
              valueFrom:
                configMapKeyRef:
                  name: oai-nr-ue-configmap
                  key: nssaiSst
            - name: NSSAI_SD
              valueFrom:
                configMapKeyRef:
                  name: oai-nr-ue-configmap
                  key: nssaiSd
            - name: USE_ADDITIONAL_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: oai-nr-ue-configmap
                  key: useAdditionalOptions
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
      dnsPolicy: ClusterFirst
      serviceAccountName: oai-nr-ue-sa
      serviceAccount: oai-nr-ue-sa
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      imagePullSecrets:
        - name: regcred
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
